"""Send EOD thesis comparison summary to Telegram."""
from __future__ import annotations
import os
import sys
from pathlib import Path
import httpx

ROOT = Path(r"C:\Users\saini\.minimax-agent\projects\kotak-neo-bot")
CREDS = ROOT / "config" / "credentials.env"

token = chat = None
if CREDS.exists():
    for line in CREDS.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.startswith("TELEGRAM_BOT_TOKEN="):
            token = line.split("=", 1)[1].strip().strip('"').strip("'")
        elif line.startswith("TELEGRAM_CHAT_ID="):
            chat = line.split("=", 1)[1].strip().strip('"').strip("'")

if not token or not chat:
    print("missing creds", file=sys.stderr)
    sys.exit(1)

msg = (
    "*EOD THESIS — Mon 31 Aug 2026 (15:35 IST)*\n"
    "\n"
    "*1) MORNING THESIS (08:25)*\n"
    "• Regime: RANGE | Bias: *neutral* (conf 30%)\n"
    "• Spot: 24175.65 | VIX: 10.68 | Range: 24013–24338 (162 pts)\n"
    "• Playbook: iron_condor / short_strangle | 45% risk, 2 max pos\n"
    "\n"
    "*2) EOD THESIS (15:35)*\n"
    "• Regime: RANGE | Bias: *neutral* (conf 30%)\n"
    "• Spot: *24080.40* | VIX: *11.16* | Range: 23911–24249 (169 pts)\n"
    "• Playbook: iron_condor / short_strangle | 45% risk, 2 max pos\n"
    "• No force-square / no-new-trade triggers\n"
    "\n"
    "*3) INTRADAY BIAS FLOW*\n"
    "• 08:25 → neutral 30% (premkt)\n"
    "• 13:30 → *bearish 100%* (news score –1.0, 113 items)\n"
    "• 14:31 → *bearish 100%* (news score –1.0, 163 items, spot 24033)\n"
    "• 15:30 → neutral 30% (flipped back at close)\n"
    "\n"
    "*4) ACTUAL vs MORNING THESIS*\n"
    "• Open→Close: 24175.65 → 24080.40 = *–95.25 pts (–0.39%)*\n"
    "• Within morning range 24013–24338? *YES*, mid-range, no breakout\n"
    "• Morning neutral: directionally WRONG (downside dominated)\n"
    "• Mid-day bearish 100% (13:30–14:31): *RIGHT* (closed near session low)\n"
    "• 15:30 neutral flip: conservative EOD; spot held below open\n"
    "• VIX 10.7 → 11.2 (mild +0.5 expansion, regime confirmed range)\n"
    "\n"
    "*5) GLOBAL CUES DELTA*\n"
    "• Crude: 85.42 → 86.60 (+1.18, inflation headwind)\n"
    "• USDINR: 95.36 → 95.15 (rupee firmer)\n"
    "• DXY: 99.60 → 99.54 (slight weaker)\n"
    "• Dow fut: 53406 → 53495 (+89)\n"
    "• BankNifty: 57496 → 58025 (+529, +0.92%, outperformed Nifty)\n"
    "\n"
    "*6) OI STRUCTURE (open vs EOD)*\n"
    "• *NOT AVAILABLE* — OI feed returned `available: false` all day\n"
    "• No max_pain / PCR / resistance / support / GEX captured\n"
    "• Strike selection: `null`\n"
    "• Note: thesis ran on price+VIX+news+xmkt only; options chain feed\n"
    "  is currently offline (same as past days — investigate OI source)\n"
    "\n"
    "*7) P&L / POSITIONS*\n"
    "• Paper cash: ₹109,977.95 (unchanged)\n"
    "• Realized: +₹9,977.95 (carried)\n"
    "• Open positions: 0 (no live trades today)\n"
    "\n"
    "_Generated by thesis_engine eod run at 15:35 IST._"
)

try:
    r = httpx.post(
        f"https://api.telegram.org/bot{token}/sendMessage",
        json={"chat_id": chat, "text": msg, "parse_mode": "Markdown",
              "disable_web_page_preview": True},
        timeout=10,
    )
    data = r.json()
    if data.get("ok"):
        print(f"sent: msg_id={data['result']['message_id']}")
    else:
        print(f"failed: {data}", file=sys.stderr)
        # retry plain text
        r2 = httpx.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat, "text": msg, "disable_web_page_preview": True},
            timeout=10,
        )
        print("plain retry:", r2.json())
except Exception as e:
    print(f"err: {e}", file=sys.stderr)
    sys.exit(1)
